"""reports — human-readable situational report formats for conflictwatch.

`intel.export` produces machine formats (GeoJSON / STIX) for tools. This module
produces the formats a *person* reads or forwards, all native and dependency-free:

  * **markdown** — a shareable situational-report brief (summary, hotspots, actors,
                   escalation trend) that renders on GitHub, in a wiki, or a chat.
  * **csv**      — the per-day timeline as CSV for a spreadsheet / quick chart.
  * **kml**      — a Google-Earth / QGIS map overlay of geolocated events, colour-coded
                   by severity (the map-overlay sibling of the GeoJSON export).
  * **intsum**   — a terse, structured INTSUM-style plaintext brief (BLUF, situation,
                   assessment) for a running log or a shift handover.

Everything is descriptive open-source reporting for situational awareness — it
summarizes *reported* events for people, and never targets, tasks, or recommends
force. Pure standard library, deterministic.
"""

from __future__ import annotations

import csv
import io
from xml.sax.saxutils import escape

from conflictwatch import analyze
from conflictwatch.events import ConflictEvent


def _events(data) -> list[ConflictEvent]:
    fields = set(ConflictEvent.__dataclass_fields__)
    out = []
    for r in (data or []):
        if isinstance(r, ConflictEvent):
            out.append(r)
        elif isinstance(r, dict):
            out.append(ConflictEvent(**{k: v for k, v in r.items() if k in fields}))
    return out


# --------------------------------------------------------------------------- #
# Markdown situational brief
# --------------------------------------------------------------------------- #
def to_markdown(events, *, window: int = 7, title: str = "Situational Report") -> str:
    evs = _events(events)
    s = analyze.summary(evs, window)
    lo, hi = s["date_range"]
    t = s["trend"]
    arrow = "▲ UP" if t["escalating"] else "▼ flat/down"
    lines = [
        f"# {title}",
        "",
        f"**Reporting period:** {lo or '—'} .. {hi or '—'}  ",
        f"**Events:** {s['total_events']}  **Reported fatalities:** {s['total_fatalities']}  ",
        f"**Escalation trend:** {arrow} — recent {t['recent']} vs prior {t['prior']} "
        f"({t['change_pct']:+}%)",
        "",
        "## Severity mix",
        "",
        "| severity | events |",
        "|---|---|",
    ]
    for sev in ("critical", "high", "medium", "low", "info"):
        if s["by_severity"].get(sev):
            lines.append(f"| {sev} | {s['by_severity'][sev]} |")
    lines += ["", "## Hotspots", "", "| country | area | events | fatalities |",
              "|---|---|---|---|"]
    for h in s["hotspots"]:
        lines.append(f"| {h['country'] or '—'} | {h['area'] or '—'} "
                     f"| {h['events']} | {h['fatalities']} |")
    lines += ["", "## Most-active actors", "", "| actor | events | fatalities |",
              "|---|---|---|"]
    for a in s["top_actors"]:
        lines.append(f"| {a['actor'] or '—'} | {a['events']} | {a['fatalities']} |")
    lines += ["", "## Event mix", ""]
    for et, c in s["by_type"].items():
        lines.append(f"- **{et}**: {c}")
    lines += ["", "---", "*Generated by conflictwatch — descriptive open-source "
              "situational awareness. Reported events only; not targeting.*", ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# CSV timeline
# --------------------------------------------------------------------------- #
def to_csv(events) -> str:
    evs = _events(events)
    rows = analyze.timeline(evs)
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(["date", "events", "fatalities"])
    for r in rows:
        w.writerow([r["date"], r["events"], r["fatalities"]])
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# KML map overlay
# --------------------------------------------------------------------------- #
_KML_COLORS = {  # KML aabbggrr (alpha,blue,green,red)
    "critical": "ff0000ff", "high": "ff0055ff", "medium": "ff00aaff",
    "low": "ff00ffff", "info": "ffaaaaaa",
}


def to_kml(events, *, name: str = "conflictwatch events") -> str:
    evs = _events(events)
    styles = "".join(
        f'<Style id="sev-{sev}"><IconStyle><color>{color}</color>'
        f'<scale>1.1</scale></IconStyle></Style>'
        for sev, color in _KML_COLORS.items())
    placemarks = []
    for e in evs:
        if e.lat is None or e.lon is None:
            continue
        desc = (f"{e.event_type} in {e.country}"
                f"{(' (' + e.location + ')') if e.location else ''} on "
                f"{e.date or 'unknown date'}; {e.fatalities} reported fatalities."
                + (f" Actors: {e.actor1}"
                   + (f" vs {e.actor2}" if e.actor2 else "") if e.actor1 else ""))
        nm = escape(f"[{e.severity}] {e.event_type} — {e.location or e.country or '?'}")
        placemarks.append(
            "<Placemark>"
            f"<name>{nm}</name>"
            f"<description>{escape(desc)}</description>"
            f"<styleUrl>#sev-{e.severity}</styleUrl>"
            f"<Point><coordinates>{e.lon},{e.lat},0</coordinates></Point>"
            "</Placemark>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<kml xmlns="http://www.opengis.net/kml/2.2"><Document>'
            f"<name>{escape(name)}</name>{styles}"
            + "".join(placemarks) +
            "</Document></kml>")


# --------------------------------------------------------------------------- #
# INTSUM-style plaintext brief
# --------------------------------------------------------------------------- #
def to_intsum(events, *, window: int = 7, area: str = "AREA OF INTEREST") -> str:
    evs = _events(events)
    s = analyze.summary(evs, window)
    lo, hi = s["date_range"]
    t = s["trend"]
    top_hs = s["hotspots"][0] if s["hotspots"] else None
    trend_word = ("ESCALATING" if t["escalating"] and t["change_pct"] >= 25
                  else "elevated" if t["escalating"] else "steady/declining")
    # BLUF: bottom line up front
    if top_hs:
        bluf = (f"{s['total_events']} reported events ({s['total_fatalities']} "
                f"fatalities) across the period; activity {trend_word}; "
                f"heaviest in {top_hs['country']} "
                f"({top_hs['area'] or 'area unspecified'}).")
    else:
        bluf = "No dated events in the reporting window."
    lines = [
        f"INTSUM — {area}",
        f"PERIOD: {lo or '—'} .. {hi or '—'}   WINDOW: {window}d",
        "=" * 60,
        "1. BLUF",
        f"   {bluf}",
        "",
        "2. SITUATION",
        f"   Events: {s['total_events']}   Fatalities: {s['total_fatalities']}",
        f"   Severity: {dict(s['by_severity'])}",
        f"   Trend: recent {t['recent']} vs prior {t['prior']} ({t['change_pct']:+}%)",
        "   Hotspots:",
    ]
    for h in s["hotspots"][:5]:
        lines.append(f"     - {h['country']} / {h['area'] or '—'}: "
                     f"{h['events']} events, {h['fatalities']} fatalities")
    lines += ["   Most-active actors:"]
    for a in s["top_actors"][:5]:
        lines.append(f"     - {a['actor']}: {a['events']} events, "
                     f"{a['fatalities']} fatalities")
    lines += [
        "",
        "3. ASSESSMENT (descriptive)",
        f"   Activity is {trend_word} over the last {window}d relative to the prior "
        f"window. Event mix: {dict(s['by_type'])}.",
        "",
        "// conflictwatch — reported open-source events only; awareness, not targeting.",
    ]
    return "\n".join(lines)


_FORMATTERS = {
    "markdown": to_markdown,
    "csv": to_csv,
    "kml": to_kml,
    "intsum": to_intsum,
}

FORMATS = tuple(_FORMATTERS)


def render(events, fmt: str, **kwargs) -> str:
    fmt = fmt.lower()
    if fmt not in _FORMATTERS:
        raise ValueError(f"unknown report format {fmt!r}; choose one of {sorted(_FORMATTERS)}")
    return _FORMATTERS[fmt](events, **kwargs)
